version: "2.2"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  petclinic:
    image: petclinic
    container_name: petclinic
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
    entrypoint: ["/dockerize", "-wait=tcp://mysql:3306", "-timeout=160s", "--", "java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]
